"""Add challenges.co_left_at

Revision ID: 08a2ce87419e
Revises: 8113245ac56b
Create Date: 2026-09-24 17:52:04.918268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a2ce87419e'
down_revision = '8113245ac56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('co_left_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('co_left_at')

    # ### end Alembic commands ###
