"""Initial schema

Revision ID: 8113245ac56b
Revises: 
Create Date: 2026-09-24 17:11:10.288873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8113245ac56b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('co_player_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'round_active', 'round_results', name='challengestatus', native_enum=False, length=20), nullable=False),
    sa.Column('current_round_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['co_player_id'], ['players.id'], name='fk_challenges_co_player_id', use_alter=True),
    sa.ForeignKeyConstraint(['current_round_id'], ['rounds.id'], name='fk_challenges_current_round_id', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('cookie_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('is_co', sa.Boolean(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'cookie_id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('puzzle', sa.String(length=20), nullable=False),
    sa.Column('scramble_text', sa.Text(), nullable=False),
    sa.Column('scramble_svg', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'complete', name='roundstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'round_number')
    )
    op.create_table('solves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('ok', 'dnf', name='solveresult', native_enum=False, length=20), nullable=True),
    sa.Column('started_inspection_at', sa.DateTime(), nullable=True),
    sa.Column('started_solve_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solves')
    op.drop_table('rounds')
    op.drop_table('players')
    op.drop_table('challenges')
    # ### end Alembic commands ###
